apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  namespace: shopping

spec:
  replicas: 2

  selector:
    matchLabels:
      app: shopping-app

  template:
    metadata:
      labels:
        app: shopping-app

    spec:
      containers:
<<<<<<< HEAD
        - name: shopping-app
=======
      - name: shopping-app
        image: bibekbajagain/nodejs-shopping:4
>>>>>>> e8e8312c7938644f3abff87657202779338a6e03

          image: bibekbajagain/nodejs-shopping:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:

            # Secret
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER

            - name: MONGO_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PWD

            # ConfigMap
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopping-config
                  key: MONGO_HOST

            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: shopping-config
                  key: MONGO_DB

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: shopping-config
                  key: PORT